version: '3.8'
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file: ./server/.env
    networks:
      - hunt-network

  frontend:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - hunt-network

networks:
  hunt-network:
    driver: bridge